version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: codemitra-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codemitra_network
    restart: unless-stopped

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: codemitra-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - codemitra_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Backend API
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: codemitra-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://root:root@postgres:5432/codemitra?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - codemitra_network
    restart: unless-stopped

  # Worker Service
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: codemitra-worker
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - WORKER_TIMEOUT=${WORKER_TIMEOUT}
      - WORKER_MEMORY_LIMIT=${WORKER_MEMORY_LIMIT}
    depends_on:
      - redis
    volumes:
      - ./worker:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - codemitra_network
    restart: unless-stopped
    privileged: true

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: codemitra-frontend
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - BACKEND_URL=http://localhost:5001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - /app/.next
    networks:
      - codemitra_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  frontend_node_modules:

networks:
  codemitra_network:
    driver: bridge
