apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: codemitra
type: Opaque
data:
  # Base64 encoded values - update these in production
  jwt-secret: eW91cl9zdXBlcl9zZWN1cmVfand0X3NlY3JldF9rZXlfaGVyZQ==
  nextauth-secret: eW91cl9uZXh0YXV0aF9zZWNyZXRfa2V5X2hlcmU=
  smtp-password: eW91cl9zbXRwX3Bhc3N3b3Jk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: codemitra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-registry/codemitra-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "postgresql://codemitra_user:secure_password@postgres:5432/codemitra_prod"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: nextauth-secret
        - name: PORT
          value: "5000"
        - name: FRONTEND_URL
          value: "https://codemitra.com"
        - name: BACKEND_URL
          value: "https://api.codemitra.com"
        - name: WORKER_TIMEOUT
          value: "30000"
        - name: MAX_CONCURRENT_EXECUTIONS
          value: "10"
        - name: RATE_LIMIT_WINDOW_MS
          value: "900000"
        - name: RATE_LIMIT_MAX_REQUESTS
          value: "100"
        - name: METRICS_ENABLED
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: codemitra
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: codemitra
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
