apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: codemitra
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "codemitra_rules.yml"
    
    scrape_configs:
      - job_name: 'codemitra-backend'
        static_configs:
          - targets: ['backend:5000']
        metrics_path: /metrics
        scrape_interval: 10s
        
      - job_name: 'codemitra-frontend'
        static_configs:
          - targets: ['frontend:3000']
        metrics_path: /metrics
        scrape_interval: 30s
        
      - job_name: 'codemitra-worker'
        static_configs:
          - targets: ['worker:8080']
        metrics_path: /metrics
        scrape_interval: 10s
        
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres:5432']
        scrape_interval: 30s
        
      - job_name: 'redis'
        static_configs:
          - targets: ['redis:6379']
        scrape_interval: 30s
        
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
            
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']
  
  codemitra_rules.yml: |
    groups:
      - name: codemitra_alerts
        rules:
          - alert: HighCPUUsage
            expr: cpu_usage_percent > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected"
              description: "CPU usage is above 80% for more than 5 minutes"
              
          - alert: HighMemoryUsage
            expr: memory_usage_percent > 85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage detected"
              description: "Memory usage is above 85% for more than 5 minutes"
              
          - alert: DatabaseConnectionFailed
            expr: database_connection_status == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Database connection failed"
              description: "Unable to connect to PostgreSQL database"
              
          - alert: RedisConnectionFailed
            expr: redis_connection_status == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Redis connection failed"
              description: "Unable to connect to Redis cache"
              
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High error rate detected"
              description: "HTTP 5xx error rate is above 10%"
              
          - alert: SlowCompilationTime
            expr: compilation_duration_seconds > 30
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Slow compilation detected"
              description: "Code compilation is taking more than 30 seconds"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: codemitra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: codemitra
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: codemitra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin123"
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: codemitra
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
